In [5]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly_express as px
import warnings 
warnings.filterwarnings('ignore')

In [6]:
mission_data = pd.read_csv("../data/VietNam_1965.csv", encoding='ISO-8859-1')
mission_data.head(20)

,THOR_DATA_VIET_ID,COUNTRYFLYINGMISSION,MILSERVICE,MSNDATE,SOURCEID,SOURCERECORD,VALID_AIRCRAFT_ROOT,TAKEOFFLOCATION,TGTLATDD_DDD_WGS84,TGTLONDDD_DDD_WGS84,...,ID,MFUNC_DESC_CLASS,NUMWEAPONSJETTISONED,NUMWEAPONSRETURNED,RELEASEALTITUDE,RELEASEFLTSPEED,RESULTSBDA,TIMEOFFTARGET,WEAPONSLOADEDWEIGHT,Year
0,445150,UNITED STATES OF AMERICA,USN,1965-11-07,849,CACTA6570,A-4,INDEPENDANCE (CVA-62),20.266666,106.100000,...,26344334,KINETIC,0,0,NaN,NaN,NaN,1721.0,-1,1965
1,445154,UNITED STATES OF AMERICA,USMC,1965-10-23,858,CACTA6570,A-4,NaN,NaN,NaN,...,26344338,KINETIC,0,0,NaN,NaN,NaN,1115.0,-1,1965
2,445161,UNITED STATES OF AMERICA,USAF,1965-11-13,897,CACTA6570,F-105,KORAT,18.283333,105.850000,...,26344345,KINETIC,0,0,NaN,NaN,NaN,1601.0,-1,1965
3,445168,UNITED STATES OF AMERICA,USAF,1965-10-01,915,CACTA6570,FC-47,BIEN HOA,10.166933,106.754357,...,26344352,KINETIC,0,0,NaN,NaN,NaN,1900.0,-1,1965
4,445172,UNITED STATES OF AMERICA,USMC,1965-10-29,946,CACTA6570,A-4,CHU LAI,15.798377,108.263525,...,26344356,KINETIC,0,0,NaN,NaN,NaN,1750.0,-1,1965
5,445173,UNITED STATES OF AMERICA,USAF,1965-11-13,948,CACTA6570,F-100,TAN SON NHUT,9.629708,105.270485,...,26344357,KINETIC,0,0,NaN,NaN,NaN,923.0,-1,1965
6,445174,UNITED STATES OF AMERICA,USAF,1965-11-10,950,CACTA6570,F-4,UBON AB,19.966666,103.583333,...,26344358,KINETIC,0,0,NaN,NaN,NaN,1042.0,-1,1965
7,445180,UNITED STATES OF AMERICA,USAF,1965-10-03,965,CACTA6570,F-105,TAKHLI,19.350000,104.266666,...,26344364,KINETIC,0,0,NaN,NaN,NaN,1206.0,-1,1965
8,445182,UNITED STATES OF AMERICA,USMC,1965-11-17,981,CACTA6570,A-4,CHU LAI,15.777936,107.232809,...,26344366,KINETIC,0,0,NaN,NaN,NaN,1324.0,-1,1965
9,445184,UNITED STATES OF AMERICA,USAF,1965-12-28,997,CACTA6570,F-4,CAM RANH BAY,12.244141,107.290785,...,26344368,KINETIC,0,0,NaN,NaN,NaN,920.0,-1,1965
10,445187,UNITED STATES OF AMERICA,USAF,1965-12-27,1020,CACTA6570,F-4,UBON AB,17.583333,105.166666,...,26344371,KINETIC,0,0,NaN,NaN,NaN,1357.0,-1,1965
11,445190,UNITED STATES OF AMERICA,USAF,1965-11-12,1038,CACTA6570,F-4,CAM RANH BAY,10.984840,108.040381,...,26344374,KINETIC,0,0,NaN,NaN,NaN,1515.0,-1,1965
12,445194,UNITED STATES OF AMERICA,USMC,1965-10-15,1050,CACTA6570,A-4,CHU LAI,15.367196,108.545761,...,26344378,KINETIC,0,0,NaN,NaN,NaN,1055.0,-1,1965
13,445200,UNITED STATES OF AMERICA,USAF,1965-10-18,1069,CACTA6570,F-102,TAN SON NHUT,9.913691,106.146480,...,26344384,KINETIC,0,0,NaN,NaN,NaN,1315.0,-1,1965
14,445202,UNITED STATES OF AMERICA,USAF,1965-12-30,1077,CACTA6570,F-4,CAM RANH BAY,14.716666,107.500000,...,26344386,KINETIC,0,0,NaN,NaN,NaN,1147.0,-1,1965
15,445205,UNITED STATES OF AMERICA,USAF,1965-10-29,1066,CACTA6570,F-4,KORAT,21.483333,103.083333,...,26344389,KINETIC,0,0,NaN,NaN,NaN,125.0,-1,1965
16,445207,UNITED STATES OF AMERICA,USAF,1965-12-07,1089,CACTA6570,F-105,TAKHLI,15.316666,107.600000,...,26344391,KINETIC,0,0,NaN,NaN,NaN,0.0,-1,1965
17,445218,UNITED STATES OF AMERICA,USAF,1965-11-26,1136,CACTA6570,F-105,KORAT,22.000000,104.550000,...,26344402,KINETIC,0,0,NaN,NaN,NaN,917.0,-1,1965
18,445219,UNITED STATES OF AMERICA,USMC,1965-11-01,1138,CACTA6570,A-4,CHU LAI,16.571778,106.904439,...,26344403,KINETIC,0,0,NaN,NaN,NaN,1625.0,-1,1965
19,445220,UNITED STATES OF AMERICA,USAF,1965-10-29,1140,CACTA6570,F-4,UBON AB,21.950000,103.883333,...,26344404,KINETIC,0,0,NaN,NaN,NaN,1335.0,-1,1965

In [7]:
def percent_missing(data):
    percents = data.isnull().sum() * 100 / len(data)
    missing_value_df = pd.DataFrame({'column_name': data.columns,'percent_missing': percents}).set_index('column_name')
    missing_value_df.sort_values('percent_missing', inplace=True)
    return missing_value_df

In [8]:
percent_missing(mission_data)

                      percent_missing
column_name
THOR_DATA_VIET_ID            0.000000
NUMWEAPONSRETURNED           0.000000
NUMWEAPONSJETTISONED         0.000000
MFUNC_DESC_CLASS             0.000000
ID                           0.000000
ADDITIONALINFO               0.000000
NUMOFACFT                    0.000000
MISSIONID                    0.000000
WEAPONSLOADEDWEIGHT          0.000000
FLTHOURS                     0.000000
AIRCRAFT_ROOT                0.000000
AIRCRAFT_ORIGINAL            0.000000
WEAPONTYPEWEIGHT             0.000000
Year                         0.000000
NUMWEAPONSDELIVERED          0.000000
COUNTRYFLYINGMISSION         0.000000
MSNDATE                      0.000000
SOURCEID                     0.000000
VALID_AIRCRAFT_ROOT          0.000000
SOURCERECORD                 0.000000
MILSERVICE                   0.002838
MFUNC                        0.002838
UNIT                         0.002838
MFUNC_DESC                   0.005676
TIMEONTARGET                 0.022703
TIMEOFFTARGET                0.022703
TAKEOFFLOCATION              0.441291
TGTTYPE                      1.021639
TGTCOUNTRY                   1.631784
TGTCONTROL                   6.386662
PERIODOFDAY                  6.544165
TGTORIGCOORDS                7.655197
OPERATIONSUPPORTED           8.136219
TGTWEATHER                   8.357574
TGTORIGCOORDSFORMAT          8.797446
TGTLATDD_DDD_WGS84           9.732529
TGTLONDDD_DDD_WGS84          9.732529
GEOZONE                     11.236609
TGTCLOUDCOVER               13.434551
WEAPONTYPE                  46.491664
CALLSIGN                   100.000000
AIRFORCESQDN               100.000000
RELEASEALTITUDE            100.000000
RELEASEFLTSPEED            100.000000
RESULTSBDA                 100.000000
AIRFORCEGROUP              100.000000
TGTID                      100.000000
WEAPONTYPECLASS            100.000000

In [10]:
mission_data.groupby('MILSERVICE').sum()['WEAPONTYPEWEIGHT']

MILSERVICE
USAF    7488539
USMC    1394794
USN     4722862
VNAF     471279
Name: WEAPONTYPEWEIGHT, dtype: int64

In [13]:
mission_data.groupby('VALID_AIRCRAFT_ROOT').sum()['WEAPONTYPEWEIGHT'].sort_values(ascending=False)

VALID_AIRCRAFT_ROOT
A-4          3460896
A-1          3029236
F-100        2590165
F-4          1792376
F-105        1271898
B-57          687804
F-8           542560
F-5           483221
A-6           139377
FC-47          18607
F-104          16819
A-3            13188
B-52            9314
F-102           5336
C-130           4188
AC-47           3057
A-5             2924
C-47            1855
KA3             1648
RF-101          1305
RF-8             565
RF-4             500
RA-5             360
RA-3             150
EA-1             100
C-117             25
EA-3               0
KA-6               0
NOT CODED          0
C-123              0
E-1                0
RB-57              0
RB-66              0
E-2                0
EF-10              0
KA-4               0
Name: WEAPONTYPEWEIGHT, dtype: int64

In [16]:
mission_data.WEAPONTYPEWEIGHT.sum()

14077474

In [30]:
mission_data.iloc[40]

THOR_DATA_VIET_ID                                                  445282
COUNTRYFLYINGMISSION                             UNITED STATES OF AMERICA
MILSERVICE                                                           USMC
MSNDATE                                                        1965-11-04
SOURCEID                                                             1351
SOURCERECORD                                                    CACTA6570
VALID_AIRCRAFT_ROOT                                                   A-4
TAKEOFFLOCATION                                                   CHU LAI
TGTLATDD_DDD_WGS84                                              15.328909
TGTLONDDD_DDD_WGS84                                             109.06206
TGTTYPE                                              UNKNOWN\UNIDENTIFIED
NUMWEAPONSDELIVERED                                                     0
TIMEONTARGET                                                       1945.0
WEAPONTYPE                                                            NaN
WEAPONTYPECLASS                                                       NaN
WEAPONTYPEWEIGHT                                                        0
AIRCRAFT_ORIGINAL                                                      A4
AIRCRAFT_ROOT                                                          A4
AIRFORCEGROUP                                                         NaN
AIRFORCESQDN                                                          NaN
CALLSIGN                                                              NaN
FLTHOURS                                                               20
MFUNC                                                                 1.0
MFUNC_DESC                                                         STRIKE
MISSIONID                                                           03179
NUMOFACFT                                                               2
OPERATIONSUPPORTED                                             IN COUNTRY
PERIODOFDAY                                                             N
UNIT                                                               M01211
TGTCLOUDCOVER                                                    OVERCAST
TGTCONTROL                                              GRND FWD AIR CNTL
TGTCOUNTRY                                                  SOUTH VIETNAM
TGTID                                                                 NaN
TGTORIGCOORDS                                                 49PBS923955
TGTORIGCOORDSFORMAT                                           ##ABC111222
TGTWEATHER                                                          1509N
ADDITIONALINFO          MISSION: VS - CONTROL_TYPE: GRND FWD AIR CNTL ...
GEOZONE                                                                BS
ID                                                               26344466
MFUNC_DESC_CLASS                                                  KINETIC
NUMWEAPONSJETTISONED                                                    0
NUMWEAPONSRETURNED                                                      0
RELEASEALTITUDE                                                       NaN
RELEASEFLTSPEED                                                       NaN
RESULTSBDA                                                            NaN
TIMEOFFTARGET                                                      1947.0
WEAPONSLOADEDWEIGHT                                                    -1
Year                                                                 1965
Name: 40, dtype: object